language: elixir

script:
  - mix format --check-formatted
  - mix credo --strict
  - travis_wait 30 mix dialyzer --halt-exit-status
  - mix test --cover

matrix:
  include:
    - elixir: '1.9.1'
      otp_release: '22.0.7'

cache:
  directories:
    - _build
    - deps
